-- MySQL Script generated by MySQL Workbench
-- Thu Apr 17 12:56:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipo` (
  `idEquipo` INT NOT NULL,
  `estado_actual` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `arena` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arbitro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Arbitro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Arbitro` (
  `idArbitro` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idArbitro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Liga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Liga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Liga` (
  `idLiga` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idLiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fecha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fecha` (
  `idFecha` INT NOT NULL,
  `temporada` VARCHAR(20) NULL,
  `dia` INT NULL,
  `mes` INT NULL,
  `año` INT NULL,
  PRIMARY KEY (`idFecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ubicacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ubicacion` (
  `idUbicacion` INT NOT NULL,
  `capacidad` VARCHAR(45) NULL,
  `arena` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jugador` (
  `idJugador` INT NOT NULL,
  `altura` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `envergadura` VARCHAR(45) NULL,
  `alcance_pie` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NULL,
  `escuela` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `equipo` VARCHAR(90) NULL,
  `estado_actual` INT NULL,
  `carrera_profesional` VARCHAR(45) NULL,
  PRIMARY KEY (`idJugador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partido` (
  `idPartido` INT NOT NULL,
  `idEquipo_Local` INT NOT NULL,
  `idEquipo_Visitante` INT NOT NULL,
  `idArbitro` INT NOT NULL,
  `idLiga` INT NOT NULL,
  `idFecha` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  `idJugador` INT NOT NULL,
  `Puntos_Totales` INT NULL,
  `Saques_Exitosos` INT NULL,
  `Saques_Fallidos` INT NULL,
  `Tiros_Dobles_Exitosos` INT NULL,
  `Tiros_Dobles_Fallidos` INT NULL,
  `Tiros_Triples_Exitosos` INT NULL,
  `Tiros_Triples_Fallidos` INT NULL,
  `Tiros_Libres_Exitosos` INT NULL,
  `Tiros_LIbres_Fallidos` INT NULL,
  `Robos_Exitosos` INT NULL,
  `Robos_Fallidos` INT NULL,
  `Rebotes_Defensivos_Obtenidos` INT NULL,
  `Rebotes_Ofensivos_Obtenidos` INT NULL,
  `Rebotes_Obtenidos` INT NULL,
  `Tiros_Bloqueados` INT NULL,
  `Perdidas_Balon` INT NULL,
  `Cambios_Jugadores` INT NULL,
  `Tiempos_Muertos` INT NULL,
  `Faltas_Personales` INT NULL,
  `Faltas_Balon_Suelto` INT NULL,
  `Faltas_Disparo` INT NULL,
  `Faltas_Rebote` INT NULL,
  `Faltas_Ofensivas` INT NULL,
  `Numero_Jugadas_Totales` INT NULL,
  `Cantidad_Ataques_Exitosos` INT NULL,
  `Cantidad_Ataques_Fallidos` INT NULL,
  `Proporcion_Exito_Ataques` FLOAT NULL,
  PRIMARY KEY (`idPartido`, `idEquipo_Local`, `idEquipo_Visitante`, `idArbitro`, `idLiga`, `idFecha`, `idUbicacion`, `idJugador`),
  INDEX `fk_Partido_Equipo_idx` (`idEquipo_Local` ASC) VISIBLE,
  INDEX `fk_Partido_Equipo1_idx` (`idEquipo_Visitante` ASC) VISIBLE,
  INDEX `fk_Partido_Arbitro1_idx` (`idArbitro` ASC) VISIBLE,
  INDEX `fk_Partido_Liga1_idx` (`idLiga` ASC) VISIBLE,
  INDEX `fk_Partido_Fecha1_idx` (`idFecha` ASC) VISIBLE,
  INDEX `fk_Partido_Ubicacion1_idx` (`idUbicacion` ASC) VISIBLE,
  INDEX `fk_Partido_Jugador1_idx` (`idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Partido_Equipo`
    FOREIGN KEY (`idEquipo_Local`)
    REFERENCES `mydb`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Equipo1`
    FOREIGN KEY (`idEquipo_Visitante`)
    REFERENCES `mydb`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Arbitro1`
    FOREIGN KEY (`idArbitro`)
    REFERENCES `mydb`.`Arbitro` (`idArbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Liga1`
    FOREIGN KEY (`idLiga`)
    REFERENCES `mydb`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Fecha1`
    FOREIGN KEY (`idFecha`)
    REFERENCES `mydb`.`Fecha` (`idFecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Ubicacion1`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Jugador1`
    FOREIGN KEY (`idJugador`)
    REFERENCES `mydb`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
